name: kemadev-REPONAMETMPL

networks:
  app:
    driver: bridge
    enable_ipv6: true

secrets:
  netrc:
    name: netrc
    environment: KEMA_NETRC

services:
  app-template:
    profiles:
      - never
    build:
      context: ../../
      dockerfile: build/Dockerfile
      target: dev
      secrets:
        - netrc
    networks:
      - app
    secrets:
      - netrc
    environment:
      # Not all projects under kemadev are private, but convenient not to set all exceptions
      GOPRIVATE: "github.com/kemadev/*"
      KEMA_RUNTIME_ENVIRONMENT: dev
      KEMA_RUNTIME_APP_NAME: REPONAMETMPL
      KEMA_RUNTIME_APP_VERSION: dev
      KEMA_RUNTIME_APP_NAMESPACE: whatever
      KEMA_OBSERVABILITY_ENDPOINT_URL: http://kemadev-REPONAMETMPL-jaeger-1:4317
      KEMA_CLIENT_DATABASE_CLIENT_ADDRESS: "postgresql://dev:dev@kemadev-REPONAMETMPL-postgresql-1:5432/dev"
      KEMA_CLIENT_CACHE_CLIENT_ADDRESS: "kemadev-REPONAMETMPL-valkey-1:6379"
      KEMA_CLIENT_CACHE_PASSWORD: "dev"
      # Set this to a strictly positive duration to export metrics to stdout
      KEMA_OBSERVABILITY_METRICS_EXPORT_INTERVAL: 0s
    ports:
      - 8080:8080
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ../../
          target: /src
    # Close immediately and let compose restart the container without waiting for graceful shutdown
    stop_grace_period: 0s

  app:
    extends:
      service: app-template
    profiles:
      - dev

  app-debug:
    extends:
      service: app-template
    profiles:
      - debug
    build:
      target: debug
    ports:
      - 50000:50000
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
