name: Docker - CI

on:
  schedule:
    # Each day at 3:00 AM
    - cron: 0 3 * * *
  pull_request:
    types:
      - opened
      - synchronize
      - unlocked
      - reopened
    paths:
      - '**Dockerfile'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  dockerfile-lint:
    name: Dockerfiles lint
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kemadev/ci-cd:latest@sha256:113f40af60f42642919c6ec9e64639e32b7ed381cb7ad5f80b5e7e1d0a6870a5
      # GitHub Actions workaround, see https://docs.github.com/en/actions/reference/dockerfile-support-for-github-actions#user
      options: --user root:root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Dockerfiles lint
        id: dockerfile-lint
        run: kema-runner docker
